### ISSUE TITLE
AttributeError: module 'lzf' has no attribute 'decompress'

### ISSUE THREAD

**Issue by aakashjuseja-aj** [VisualComputingInstitute/Person_MinkUNet#1] opened 2022-01-29 23:54 UTC
2022-01-29 18:46:54,723  DEBUG  Log directory: /home/aakashkumar/Downloads/projects/minkunet/Person_MinkUNet/logs/unet_bl_voxel_jrdb_0.05_0.1_EVAL_20220129_184654
2022-01-29 18:46:54,723  DEBUG  Backup unet_bl_voxel_jrdb_0.05_0.1.yaml
2022-01-29 18:46:54,724   INFO  CUDA_VISIBLE_DEVICES=ALL
2022-01-29 18:46:54,726  DEBUG  Pipeline starts.
Traceback (most recent call last):
  File "/home/aakashkumar/Downloads/projects/minkunet/Person_MinkUNet/bin/train.py", line 98, in <module>
    pipeline.load_ckpt(model, args.ckpt)
  File "/home/aakashkumar/Downloads/projects/minkunet/Person_MinkUNet/lidar_det/pipeline/pipeline.py", line 37, in load_ckpt
    epoch, step = self.logger.load_ckpt(ckpt, model, self.optim)
  File "/home/aakashkumar/Downloads/projects/minkunet/Person_MinkUNet/lidar_det/pipeline/logger.py", line 195, in load_ckpt
    ckpt = torch.load(fname)
  File "/home/aakashkumar/anaconda3/envs/minkunet_clone/lib/python3.9/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/aakashkumar/anaconda3/envs/minkunet_clone/lib/python3.9/site-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\xd4'.
(minkunet_clone) aakashkumar@lynx173876:~/Downloads/projects/minkunet/Person_MinkUNet$ python3 bin/train.py --cfg unet_bl_voxel_jrdb_0.05_0.1.yaml --ckpt ckpt_e40_train_val.pth --evaluation
2022-01-29 18:47:49,851  DEBUG  Log directory: /home/aakashkumar/Downloads/projects/minkunet/Person_MinkUNet/logs/unet_bl_voxel_jrdb_0.05_0.1_EVAL_20220129_184749
2022-01-29 18:47:49,851  DEBUG  Backup unet_bl_voxel_jrdb_0.05_0.1.yaml
2022-01-29 18:47:49,852   INFO  CUDA_VISIBLE_DEVICES=ALL
2022-01-29 18:47:49,853  DEBUG  Pipeline starts.
2022-01-29 18:47:50,080   INFO  Load checkpoint ckpt_e40_train_val.pth: epoch 40, step 31080.
2022-01-29 18:47:50,085  DEBUG  Evaluation starts.
eval (val) (0/40):   0%|                                                                                                                                        | 0/6203 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/aakashkumar/Downloads/projects/minkunet/Person_MinkUNet/bin/train.py", line 106, in <module>
    run_evaluation(model, pipeline, cfg)
  File "/home/aakashkumar/Downloads/projects/minkunet/Person_MinkUNet/bin/train.py", line 40, in run_evaluation
    pipeline.evaluate(model, val_loader, tb_prefix="VAL", rm_files=False)
  File "/home/aakashkumar/Downloads/projects/minkunet/Person_MinkUNet/lidar_det/pipeline/pipeline.py", line 25, in evaluate
    status = self.trainer.evaluate(
  File "/home/aakashkumar/Downloads/projects/minkunet/Person_MinkUNet/lidar_det/pipeline/trainer.py", line 61, in evaluate
    for b_idx, batch in enumerate(eval_loader):
  File "/home/aakashkumar/anaconda3/envs/minkunet_clone/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/aakashkumar/anaconda3/envs/minkunet_clone/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/aakashkumar/anaconda3/envs/minkunet_clone/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/aakashkumar/anaconda3/envs/minkunet_clone/lib/python3.9/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/aakashkumar/anaconda3/envs/minkunet_clone/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/aakashkumar/anaconda3/envs/minkunet_clone/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/aakashkumar/anaconda3/envs/minkunet_clone/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/aakashkumar/Downloads/projects/minkunet/Person_MinkUNet/lidar_det/dataset/dataset_det3d.py", line 83, in __getitem__
    data_dict = self.__handle[idx]
  File "/home/aakashkumar/Downloads/projects/minkunet/Person_MinkUNet/lidar_det/dataset/handles/jrdb_handle.py", line 73, in __getitem__
    "pc_upper": self.load_pointcloud(urls["pc_upper"]),
  File "/home/aakashkumar/Downloads/projects/minkunet/Person_MinkUNet/lidar_det/dataset/handles/jrdb_handle.py", line 104, in load_pointcloud
    pc = point_cloud_from_path(url).pc_data
  File "/home/aakashkumar/Downloads/projects/minkunet/Person_MinkUNet/lidar_det/dataset/handles/_pypcd.py", line 307, in point_cloud_from_path
    pc = point_cloud_from_fileobj(f)
  File "/home/aakashkumar/Downloads/projects/minkunet/Person_MinkUNet/lidar_det/dataset/handles/_pypcd.py", line 296, in point_cloud_from_fileobj
    pc_data = parse_binary_compressed_pc_data(f, dtype, metadata)
  File "/home/aakashkumar/Downloads/projects/minkunet/Person_MinkUNet/lidar_det/dataset/handles/_pypcd.py", line 264, in parse_binary_compressed_pc_data
    buf = lzf.decompress(compressed_data, uncompressed_size)
AttributeError: module 'lzf' has no attribute 'decompress'

**Comment by danjia21** [comment] 2022-01-30 17:13
Can you try with `python-lzf==0.2.4`?

**Comment by danjia21** [comment] 2022-02-01 13:57
@BravoCharlie-ai if the problem is solved, can you close the issue?

**Closed as completed** 2022-02-14 21:00 UTC
